on:
  push:
    paths:
      - 'linux'
jobs:
  download-linux:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Download Linux
      run: |
        sudo apt install gcc-8
        cd linux
        wget https://github.com/Tim3s/linux/archive/$(git log --format="%H" -n 1).zip
        unzip csi2115-hw2.zip
        cd ..
        ./build-linux.sh linux/linux-csi2115-hw2 tinyconfig
