on:
  push:
    paths:
      - 'linux'
jobs:
  download-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Download Linux
      run: |
        echo $(PWD)
        wget https://github.com/Tim3s/linux/archive/csi2115-hw2.zip
        echo $(PWD)
        cd ..
        apt-get install unzip
        cd scripts
        unzip csi2115-hw2.zip
        ./build-linux.sh linux-csi2115-hw2 tinyconfig
