on:
  push:
    paths:
      - 'linux'
jobs:
  download-linux:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Download Linux
      run: |
        wget https://github.com/Tim3s/linux/archive/csi2115-hw2.zip
        unzip csi2115-hw2.zip
        ./build-linux.sh linux-csi2115-hw2 tinyconfig
