
on:
  push:
    paths:
       - 'test/**'
jobs:
  compile-test:
    runs-on: ubuntu-20.04
    defualts:
      run:
        working-directory: test
    steps:
    - name: Compile Test
      run: |
        make -C test
