
on:
  push:
    paths:
       - 'test/**'
jobs:
  compile-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts
    steps:
    - name: Compile Test
      run: |
        ls
        make -C test
